FROM python:3.10-slim

# In a non-development environment, you should not use the --reload flag
# Also in a non-development environment, I should be copying the source code
# into the image, and not mounting it as a volume (see docker-compose.yml)

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    apt-get install -y unixodbc-dev && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 && \
    rm -rf /var/lib/apt/lists/*

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]